// Immutable startup manifest. Only a fully downloaded shell can activate.
self.BARK_OFFLINE_CACHE_MANIFEST = Object.freeze({
    "version": "0.144",
    "entry": "./index.v144.html",
    "shell": [
        "./index.v144.html",
        "./version.json",
        "./assets/data/bark-fallback-0.142.csv",
        "./assets/images/bark-tag.jpeg",
        "./assets/images/usbarkrangers-qr.jpeg",
        "./assets/images/WatermarkBARK.PNG",
        "./pages/privacy.html",
        "./pages/terms.html",
        "./vendor/leaflet-1.9.4/images/layers.png",
        "./vendor/leaflet-1.9.4/images/layers-2x.png",
        "./vendor/leaflet-1.9.4/images/marker-icon.png",
        "./vendor/leaflet-1.9.4/images/marker-icon-2x.png",
        "./vendor/leaflet-1.9.4/images/marker-shadow.png",
        "./offline/offlineBootstrap.js?v=1",
        "./vendor/leaflet-1.9.4/leaflet.css",
        "./vendor/leaflet-1.9.4/leaflet.js",
        "./vendor/markercluster-1.4.1/MarkerCluster.css",
        "./vendor/markercluster-1.4.1/MarkerCluster.Default.css",
        "./vendor/markercluster-1.4.1/leaflet.markercluster.js",
        "./vendor/turf-6.5.0/turf.min.js",
        "./styles.v141.css",
        "./styles/mapStyles.css?v=6",
        "./styles/trophyCase.css?v=8",
        "./styles/feedbackModal.css?v=2",
        "./styles/watermarkTool.css?v=2",
        "./styles/walkTracker.css?v=2",
        "./styles/viewportShell.css?v=5",
        "./styles/loadState.css?v=1",
        "./modules/viewportCoordinator.js?v=7",
        "./styles/riskyAndroidDesktopViewportRecovery.css?v=6",
        "./modules/riskyAndroidDesktopViewportRecovery.js?v=1",
        "./manifest.json",
        "./assets/images/bark-logo.jpeg",
        "./vendor/firebase-10.11.0/firebase-app-compat.js",
        "./vendor/firebase-10.11.0/firebase-app-check-compat.js",
        "./vendor/firebase-10.11.0/firebase-auth-compat.js",
        "./vendor/firebase-10.11.0/firebase-firestore-compat.js",
        "./vendor/firebase-10.11.0/firebase-functions-compat.js",
        "./vendor/firebase-10.11.0/firebase-analytics-compat.js",
        "./vendor/papaparse-5.4.1/papaparse.min.js",
        "./modules/monitoringContext.js?v=5",
        "./modules/errorReporter.js?v=7",
        "./modules/rateLimitUi.js?v=3",
        "./utils/geoUtils.js?v=2",
        "./utils/scoringUtils.js?v=2",
        "./utils/imageDownscale.js?v=2",
        "./gamificationLogic.js?v=10",
        "./MapMarkerConfig.js?v=4",
        "./modules/settingsRegistry.js?v=3",
        "./repos/ParkRepo.js?v=2",
        "./repos/VaultRepo.v141.js",
        "./modules/launchFlags.js?v=1",
        "./modules/barkState.js?v=17",
        "./modules/barkConfig.js?v=9",
        "./modules/loadState.js?v=1",
        "./modules/visitorAnalytics.js?v=1",
        "./config/domRefs.js?v=4",
        "./state/settingsStore.js?v=6",
        "./state/appState.js?v=4",
        "./modules/RefreshCoordinator.js?v=2",
        "./services/orsRouteCache.js?v=2",
        "./services/orsService.js?v=8",
        "./services/visitMutationCoordinator.v141.js",
        "./services/firebaseService.v141.js",
        "./renderers/routeRenderer.js?v=6",
        "./services/checkinService.v141.js",
        "./services/authPremiumUi.js?v=5",
        "./services/premiumService.js?v=3",
        "./services/authAccountUi.js?v=26",
        "./modules/feedbackTransport.js?v=7",
        "./modules/paywallController.js?v=24",
        "./services/authService.v141.js",
        "./modules/markerLayerPolicy.js?v=2",
        "./modules/MarkerLayerManager.js?v=19",
        "./engines/tripRoutePlan.js?v=3",
        "./engines/tripRouteBatch.js?v=4",
        "./modules/TripLayerManager.js?v=14",
        "./modules/mapEngine.v143.js",
        "./modules/renderEngine.js?v=14",
        "./renderers/panelRenderer.js?v=31",
        "./modules/externalPinReturn.js?v=5",
        "./modules/searchEngine.js?v=10",
        "./modules/dataService.v143.js",
        "./renderers/leaderboardRenderer.js?v=1",
        "./modules/achievementsPanel.js?v=1",
        "./modules/managePortal.js?v=2",
        "./modules/profileEngine.js?v=18",
        "./modules/leaderboardSyncPolicy.js?v=1",
        "./modules/leaderboardEngine.js?v=4",
        "./modules/expeditionEngine.js?v=11",
        "./modules/walkTracker.js?v=4",
        "./engines/tripPlannerCore.js?v=28",
        "./modules/shareEngine.js?v=10",
        "./modules/watermarkTool.js?v=5",
        "./modules/settingsController.js?v=13",
        "./modules/uiController.js?v=30",
        "./modules/firstOpenDisclaimer.js?v=2",
        "./modules/feedbackSubjectPicker.js?v=2",
        "./modules/feedbackModal.js?v=6",
        "./core/app.v144.js"
    ],
    "criticalExternal": [],
    "navigationTimeoutMs": 1800,
    "staticTimeoutMs": 4000,
    "tileTimeoutMs": 4000,
    "minimumOfflineTileZoom": 11,
    "maximumOfflineTiles": 350,
    "legacyExternal": {
        "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js": "./vendor/leaflet-1.9.4/leaflet.js",
        "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css": "./vendor/leaflet-1.9.4/leaflet.css",
        "https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js": "./vendor/markercluster-1.4.1/leaflet.markercluster.js",
        "https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css": "./vendor/markercluster-1.4.1/MarkerCluster.css",
        "https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css": "./vendor/markercluster-1.4.1/MarkerCluster.Default.css",
        "https://cdn.jsdelivr.net/npm/@turf/turf@6.5.0/turf.min.js": "./vendor/turf-6.5.0/turf.min.js",
        "https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js": "./vendor/papaparse-5.4.1/papaparse.min.js",
        "https://www.gstatic.com/firebasejs/10.11.0/firebase-app-compat.js": "./vendor/firebase-10.11.0/firebase-app-compat.js",
        "https://www.gstatic.com/firebasejs/10.11.0/firebase-app-check-compat.js": "./vendor/firebase-10.11.0/firebase-app-check-compat.js",
        "https://www.gstatic.com/firebasejs/10.11.0/firebase-auth-compat.js": "./vendor/firebase-10.11.0/firebase-auth-compat.js",
        "https://www.gstatic.com/firebasejs/10.11.0/firebase-firestore-compat.js": "./vendor/firebase-10.11.0/firebase-firestore-compat.js",
        "https://www.gstatic.com/firebasejs/10.11.0/firebase-functions-compat.js": "./vendor/firebase-10.11.0/firebase-functions-compat.js",
        "https://www.gstatic.com/firebasejs/10.11.0/firebase-analytics-compat.js": "./vendor/firebase-10.11.0/firebase-analytics-compat.js",
        "https://cdn.jsdelivr.net/npm/@turf/turf@6/turf.min.js": "./vendor/turf-6.5.0/turf.min.js"
    }
});
