/**
 * cacheManifest.js — versioned, minimum application shell for offline startup.
 *
 * This file is imported only by sw.js. Keep cloud/API responses out of this
 * list: it contains executable/static resources required to open the SPA,
 * render cached parks, and restore locally journaled visit mutations.
 */
self.BARK_OFFLINE_CACHE_MANIFEST = Object.freeze({
    version: '0.140',
    shell: Object.freeze([
        './',
        './index.html',
        './manifest.json',
        './version.json',
        './assets/data/bark-fallback.csv',
        './assets/images/bark-logo.jpeg',
        './assets/images/bark-tag.jpeg',
        './assets/images/usbarkrangers-qr.jpeg',
        './assets/images/WatermarkBARK.PNG',
        './styles.css?v=87',
        './styles/mapStyles.css?v=6',
        './styles/trophyCase.css?v=8',
        './styles/feedbackModal.css?v=2',
        './styles/watermarkTool.css?v=2',
        './styles/walkTracker.css?v=2',
        './styles/viewportShell.css?v=5',
        './styles/loadState.css?v=1',
        './styles/riskyAndroidDesktopViewportRecovery.css?v=6',
        './modules/oauthFragmentGuard.js?v=1',
        './modules/viewportCoordinator.js?v=7',
        './modules/riskyAndroidDesktopViewportRecovery.js?v=1',
        './modules/monitoringContext.js?v=5',
        './modules/errorReporter.js?v=7',
        './modules/rateLimitUi.js?v=3',
        './utils/geoUtils.js?v=2',
        './utils/scoringUtils.js?v=2',
        './utils/imageDownscale.js?v=2',
        './gamificationLogic.js?v=10',
        './MapMarkerConfig.js?v=4',
        './modules/settingsRegistry.js?v=3',
        './repos/ParkRepo.js?v=2',
        './repos/VaultRepo.js?v=6',
        './modules/launchFlags.js?v=1',
        './modules/barkState.js?v=17',
        './modules/barkConfig.js?v=9',
        './modules/loadState.js?v=1',
        './modules/visitorAnalytics.js?v=1',
        './config/domRefs.js?v=4',
        './state/settingsStore.js?v=6',
        './state/appState.js?v=4',
        './modules/RefreshCoordinator.js?v=2',
        './services/orsRouteCache.js?v=2',
        './services/orsService.js?v=8',
        './services/visitMutationCoordinator.js?v=2',
        './services/firebaseService.js?v=25',
        './renderers/routeRenderer.js?v=6',
        './services/checkinService.js?v=28',
        './services/authPremiumUi.js?v=5',
        './services/premiumService.js?v=3',
        './services/authAccountUi.js?v=26',
        './modules/feedbackTransport.js?v=7',
        './modules/paywallController.js?v=24',
        './services/authService.js?v=86',
        './modules/markerLayerPolicy.js?v=2',
        './modules/MarkerLayerManager.js?v=19',
        './engines/tripRoutePlan.js?v=3',
        './engines/tripRouteBatch.js?v=4',
        './modules/TripLayerManager.js?v=14',
        './modules/mapEngine.js?v=5',
        './modules/renderEngine.js?v=14',
        './renderers/panelRenderer.js?v=31',
        './modules/externalPinReturn.js?v=5',
        './modules/searchEngine.js?v=10',
        './modules/dataService.js?v=12',
        './renderers/leaderboardRenderer.js?v=1',
        './modules/achievementsPanel.js?v=1',
        './modules/managePortal.js?v=2',
        './modules/profileEngine.js?v=18',
        './modules/leaderboardSyncPolicy.js?v=1',
        './modules/leaderboardEngine.js?v=4',
        './modules/expeditionEngine.js?v=11',
        './modules/walkTracker.js?v=4',
        './engines/tripPlannerCore.js?v=28',
        './modules/shareEngine.js?v=10',
        './modules/watermarkTool.js?v=5',
        './modules/settingsController.js?v=13',
        './modules/uiController.js?v=30',
        './modules/firstOpenDisclaimer.js?v=2',
        './modules/feedbackSubjectPicker.js?v=2',
        './modules/feedbackModal.js?v=6',
        './core/app.js?v=39',
        './offline/offlineBootstrap.js?v=1',
        './pages/privacy.html',
        './pages/terms.html'
    ]),
    criticalExternal: Object.freeze([
        'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
        'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',
        'https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css',
        'https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css',
        'https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js',
        'https://cdn.jsdelivr.net/npm/@turf/turf@6/turf.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js',
        'https://www.gstatic.com/firebasejs/10.11.0/firebase-app-compat.js',
        'https://www.gstatic.com/firebasejs/10.11.0/firebase-app-check-compat.js',
        'https://www.gstatic.com/firebasejs/10.11.0/firebase-auth-compat.js',
        'https://www.gstatic.com/firebasejs/10.11.0/firebase-firestore-compat.js',
        'https://www.gstatic.com/firebasejs/10.11.0/firebase-functions-compat.js',
        'https://www.gstatic.com/firebasejs/10.11.0/firebase-analytics-compat.js'
    ]),
    navigationTimeoutMs: 1800,
    minimumOfflineTileZoom: 11,
    maximumOfflineTiles: 350
});
